# Generated by Django 4.0.5 on 2022-07-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name="Serie's name")),
                ('description', models.TextField(blank=True, null=True, verbose_name="Serie's description")),
            ],
        ),
        migrations.DeleteModel(
            name='Series',
        ),
    ]
