# Generated by Django 4.0.5 on 2022-07-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0002_serie_delete_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name="Publisher's name")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Publisher description')),
                ('genre', models.ManyToManyField(to='handbook.genre')),
            ],
        ),
    ]
