# Generated by Django 4.0.5 on 2022-07-09 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0003_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
