# Generated by Django 4.0.5 on 2022-07-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0005_alter_author_name_alter_genre_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name="Book's name")),
                ('description', models.TextField(blank=True, null=True, verbose_name="Book's description")),
            ],
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name="Genre's name"),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name="Publisher's name"),
        ),
        migrations.AlterField(
            model_name='serie',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name="Serie's name"),
        ),
    ]
