# Generated by Django 4.0.5 on 2022-07-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0006_book_alter_genre_name_alter_publisher_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='handbook.author'),
        ),
    ]
