# Generated by Django 4.0.5 on 2022-07-10 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0007_book_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
