# Generated by Django 4.0.5 on 2022-07-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0009_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Book description'),
        ),
        migrations.AlterField(
            model_name='book',
            name='date_of_modified',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Date of entry'),
        ),
    ]
