# Generated by Django 4.0.5 on 2022-07-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0010_book_description_alter_book_date_of_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='age_restrictions',
            field=models.IntegerField(blank=True, null=True, verbose_name='age restrictions'),
        ),
        migrations.AlterField(
            model_name='book',
            name='date_of_entry',
            field=models.DateField(blank=True, null=True, verbose_name='Date of entry'),
        ),
        migrations.AlterField(
            model_name='book',
            name='date_of_modified',
            field=models.DateField(blank=True, null=True, verbose_name='Date of modified'),
        ),
    ]
