# Generated by Django 4.0.5 on 2022-07-27 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0012_alter_book_date_of_entry_alter_book_date_of_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_of_entry',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Date of entry'),
        ),
        migrations.AlterField(
            model_name='book',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='series', to='handbook.serie', verbose_name='Serie'),
        ),
    ]
