# Generated by Django 4.0.5 on 2022-07-29 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0013_alter_book_date_of_entry_alter_book_series'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
