# Generated by Django 4.0.5 on 2022-08-09 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_bookincart_created_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.cart', verbose_name='Cart')),
            ],
        ),
    ]
