# Generated by Django 4.0.5 on 2022-08-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Phone'),
        ),
    ]
