# Generated by Django 4.0.5 on 2022-08-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderstatus_alter_order_address_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'created'), (2, 'accepted for processing'), (3, 'assembled'), (4, 'handed over for delivery'), (5, 'delivered')], default=1),
        ),
    ]
