# Generated by Django 4.0.5 on 2022-08-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_status_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='status',
        ),
        migrations.AddField(
            model_name='status',
            name='name',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Name'),
        ),
    ]
